### PR TITLE
overflow fixed for Chrome and Opera Navigator

### PR DESCRIPTION
**Pull request by JasminDreasond**
you project is a big help for me. I want to help you too with this code. ^~^
This is a code to fix some tiny problems on scrollbar style for Opera Navigator. The navigator needs it to fix some scrollbar style problems.

### CODE REVIEW

**Comment by Shade-** [comment]
Can someone with a Windows environment test this please? @Eldenroot

**Comment by Shade-** [comment]
Oh well, I've tested on my Mac and this breaks the entire scrolling. I'm sorry but I have to reject this. Thank you for contributing anyway :)

**Comment by JasminDreasond** [comment]
You need to adapt the code to work on navegator that needs it only. :p 
the code works correctly here. The code is to fix this problem that happen in my navegator.
I use Windows 10 and my navegator is Opera.

The image from the problem that happen on my computer:


The problem was posted on a issue here for a second user too:
https://github.com/Shade-/FASTyle/issues/8

**Comment by Shade-** [comment]
FASTyle 2.1 has introduced the issue, a rollback is sufficient. I can’t merge this as the code does not have to be adapted everytime but it should be tested to work in every browser and environment.

**Comment by JasminDreasond** [comment]
> work in every browser and environment.

that's what I'm talking about, sorry if you got it wrong. sometimes is hard write english becase it is not my native language x-x

Trying to say better my message: The code needs to work on browser that really needs the code to fix it.

**Comment by JasminDreasond** [comment]
thanks for listening ^~^

**Comment by Shade-** [comment]
Yeah well, you can rollback to v2.0 to solve. v2.2 is coming anyway.

**Pull request closed without merging**
